Traceback (most recent call last):
  File "/home/ssadyr/devs/newKernel/automation/errorExample.py", line 15, in <module>
    raise Exception("Это сообщение об ощибке.")
Exception: Это сообщение об ощибке.
